# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2c96495c3b6ff78432c83d9c4df7ea152afaa48b6ebec93c333b0fc329adc7ddeb837fe6c87dc762e8a9ad256c545e6c4c6a98d63d92520dbbe0db4f137cb488

test:
  secret_key_base: 2ebc46b56335e718f5a2208ea52926ed91e0005eabfa355577f39007f46cca362a5c45e6f5afcafe2711ee3e31173ed031bbb79fda86fea54e80fbcaebce895f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
